### PR TITLE
Converting the CSS to a SCSS structure

### PR DESCRIPTION
**Pull request by ynnoj**
Introducing a clearer SCSS structure for the addon.

* All the CSS is now compiled to `vendor.css`
* Vendor prefixing is handled by [ember-cli-autoprefixer](https://github.com/kimroen/ember-cli-autoprefixer)

One problem I was unable to solve was the separation of the theme stylesheets and the import based on `config/environment.js`. I've removed that as part of this initial commit. I'm not sure if this is something that you want to remain @knownasilya, but it would be nice if we could get the best of both implementations.

### CODE REVIEW

**Comment by knownasilya** [comment]
I prefer Less, but Sass (not that familiar with it) is fine I guess :smile:, although I do want to keep it configurable, so I'm not going to merge this just yet.

If you have ideas on how to keep it configurable, that would help move this along.

**Comment by ynnoj** [comment]
@knownasilya I'll keep at it 👍

**Comment by mansona** [comment]
Hi Folks, I'm just helping @ynnoj here with the build system and i'm trying to make use of the treeForStyles hook in the ember addon. The plan was for it to decide which theme to include in the index.js file so that you could define a configuration entry in the consuming App to specify which theme to include. 

Unfortunately my ember-cli-fu has failed me this time :sob: Maybe it's time to get some external help from someone on the ember-cli team to see if this is even the right avenue to be taking. Maybe reach out to @rwjblue ?

**Comment by knownasilya** [comment]
I'm going to close this, since there hasn't been any movement. Feel free to submit a fresh PR (or ask me to reopen) if you are still working on this.

**Pull request closed without merging**
