### PR TITLE
Update ember-cli to 2.11

### PR DESCRIPTION
**Pull request by cibernox**

### CODE REVIEW

**Comment by knownasilya** [comment]
Ready for merge?

**Comment by cibernox** [comment]
This fails because the bug present in 2.10+.

I'm actually not sure how to fix it, since seems that the component is doing by design something forbidden, here: https://github.com/knownasilya/ember-cli-toggle/blob/master/addon/components/x-toggle/component.js#L34-L39

This pattern was discouraged before but since glimmer2 is just forbidden.

**Comment by knownasilya** [comment]
Maybe just wrapping it in `Ember.run.next`?

**Comment by cibernox** [comment]
Perhaps that could work, although I didn't get exactly why the component wants to immediately set the value on the outside when it's undefined. Shouldn't `undefined` be treated as `falsey` and just don't do anything?

**Comment by knownasilya** [comment]
These are historic changes by @ksnyde, which helped his usecase. Looking back it was probably too specific for the general public. I'd make it simpler and release a 3.0.

**Comment by LevelbossMike** [comment]
:+1: Thanks for this change. Can we release a patch release for this please? Running into that right now with ember-stable (2.11.0).

**Comment by knownasilya** [comment]
Released as v3.0.0

**Comment by LevelbossMike** [comment]
cool thx so much 🍻

**Pull request merged**
