### PR TITLE
Start v1 API changes

### PR DESCRIPTION
**Pull request by knownasilya**
Follow "Data Down, Actions Up" methodology.

Also removes labels, see https://github.com/knownasilya/ember-cli-toggle/issues/24#issuecomment-111121725

### CODE REVIEW

**Comment by gzurbach** [comment]
I tried to switch to master this morning and I'm having an issue:
`Uncaught Error: Could not find module 'ember-cli-toggle/components/x-toggle/template' imported from 'ember-cli-toggle/components/x-toggle/component'`

Seems like a very simple `import` issue. 

I wanted to update because I'm not able to write acceptance tests with 0.5.8, they blow up on this lines:

```javascript
var offIndex = this.get('off').indexOf(':');
var onIndex = this.get('on').indexOf(':');
```

Seems like `this.get('off')` is null. It works fine when used in the app but it throws during testing. I think your latest changes will likely fix that issue because the observer is no fired `on('init')` anymore. But I might be wrong.

**Comment by knownasilya** [comment]
@gzurbach that sounds wrong, maybe it didn't install correctly, or you have an old version of ember-cli in your app.

**Comment by gzurbach** [comment]
Hmm I'm on 0.2.5. Maybe I should try with 0.2.7?

**Comment by knownasilya** [comment]
Is that the version that your project is on?

**Comment by gzurbach** [comment]
Yep

**Comment by gzurbach** [comment]
Apparently one of my co-workers is trying to upgrade to 0.2.7 this morning. I will get back to you if it changes anything.

**Comment by gzurbach** [comment]
Hey! I think things are looking good now (using 0.2.7). Do you know when will you release the next version? We are experiencing a bunch of deprecation warnings with Ember 1.13 because 0.5.8 is still using `bind-attr`.
Thanks!

**Comment by knownasilya** [comment]
Sounds good, should be released early next week.

**Pull request merged**
